---
title: "Første utkast Mappe oppgave 1"
author: "Idunn, Sofia og Erlend"
date: "20 3 2022"
output: pdf_document
---

# Mappeoppgave 1 

## første utkast mappe 1 Kode


```{r datasets and librarys, include=FALSE}
#install.packages("rjstat")
#install.packages("gdata")
#install.packages("janitor")


library(tidyverse)
library(httr)
library(rjstat)
library(gdata)
library(janitor)
library(lubridate)

#laste inn datasett
url <- "https://data.ssb.no/api/v0/no/table/03013"
url1 <- "https://www.ssb.no/statbank/sq/10064781"

#ta inn spørringen
data <-
  '
{
  "query": [
    {
      "code": "Konsumgrp",
      "selection": {
        "filter": "vs:CoiCop2016niva3",
        "values": [
          "01.1",
          "01.2",
          "02.1",
          "02.2",
          "03.1",
          "03.2",
          "04.1",
          "04.2",
          "04.3",
          "04.4",
          "04.5",
          "05.1",
          "05.2",
          "05.3",
          "05.4",
          "05.5",
          "05.6",
          "06.1",
          "06.2",
          "07.1",
          "07.2",
          "07.3",
          "08.1",
          "08.2",
          "08.3",
          "09.1",
          "09.2",
          "09.3",
          "09.4",
          "09.5",
          "09.6",
          "11.1",
          "11.2",
          "12.1",
          "12.3",
          "12.4",
          "12.5",
          "12.6",
          "12.7"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "item",
        "values": [
          "2012M01",
          "2012M02",
          "2012M03",
          "2012M04",
          "2012M05",
          "2012M06",
          "2012M07",
          "2012M08",
          "2012M09",
          "2012M10",
          "2012M11",
          "2012M12",
          "2013M01",
          "2013M02",
          "2013M03",
          "2013M04",
          "2013M05",
          "2013M06",
          "2013M07",
          "2013M08",
          "2013M09",
          "2013M10",
          "2013M11",
          "2013M12",
          "2014M01",
          "2014M02",
          "2014M03",
          "2014M04",
          "2014M05",
          "2014M06",
          "2014M07",
          "2014M08",
          "2014M09",
          "2014M10",
          "2014M11",
          "2014M12",
          "2015M01",
          "2015M02",
          "2015M03",
          "2015M04",
          "2015M05",
          "2015M06",
          "2015M07",
          "2015M08",
          "2015M09",
          "2015M10",
          "2015M11",
          "2015M12",
          "2016M01",
          "2016M02",
          "2016M03",
          "2016M04",
          "2016M05",
          "2016M06",
          "2016M07",
          "2016M08",
          "2016M09",
          "2016M10",
          "2016M11",
          "2016M12",
          "2017M01",
          "2017M02",
          "2017M03",
          "2017M04",
          "2017M05",
          "2017M06",
          "2017M07",
          "2017M08",
          "2017M09",
          "2017M10",
          "2017M11",
          "2017M12",
          "2018M01",
          "2018M02",
          "2018M03",
          "2018M04",
          "2018M05",
          "2018M06",
          "2018M07",
          "2018M08",
          "2018M09",
          "2018M10",
          "2018M11",
          "2018M12",
          "2019M01",
          "2019M02",
          "2019M03",
          "2019M04",
          "2019M05",
          "2019M06",
          "2019M07",
          "2019M08",
          "2019M09",
          "2019M10",
          "2019M11",
          "2019M12",
          "2020M01",
          "2020M02",
          "2020M03",
          "2020M04",
          "2020M05",
          "2020M06",
          "2020M07",
          "2020M08",
          "2020M09",
          "2020M10",
          "2020M11",
          "2020M12",
          "2021M01",
          "2021M02",
          "2021M03",
          "2021M04",
          "2021M05",
          "2021M06",
          "2021M07",
          "2021M08",
          "2021M09",
          "2021M10",
          "2021M11",
          "2021M12",
          "2022M01",
          "2022M02"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}

  '

d.tmp <- POST(url , body = data, encode = "json", verbose())

d.tmp2 <- POST(url1 , body = data, encode = "json", verbose())

sbtabell <- fromJSONstat(content(d.tmp, "text"))

totaltabell <- fromJSONstat(content(d.tmp2, "text"))

#for å få fyste delen
ds <- sbtabell[[1]]
ds

#binda dsei elns

kpi <- rbind(sbtabell, totaltabell)

#laga eikn tibble
as_tibble(kpi)
```


```{r datawrangling, echo=TRUE}
# rydde i navna
clean_names(kpi)

#sepererer månder og år

kpi <- kpi %>%
  separate(måned, into=c("year", "month"), sep="M") %>%
  mutate(dato = ymd(paste(year, month, "15")))

#lage den breiere

kpi <- kpi %>%
  pivot_wider(names_from = statistikkvariabel, values_from = value)

#forandre vekter til totalindeks

kpi <- kpi %>%
  mutate(vekter = `Konsumprisindeks (vekter)`/1000) %>%
  select(-c(`Konsumprisindeks (vekter)`, year, month))



#kpi%>% group_by(konsumgruppe)%>%
 # mutate(dp=(indeks - lag(indeks,12)),
  #       adp=vekter*dp)

#filter(Totalindeks)
#group_by(dato)%>%
  #mutate(dpdP=sadp/dplyr::lag(totalindeks))  

#dp= ending i 12 måned pris

#laga plott med  tid på den horisontale aksen samt totalindeksen og indeksen for elektrisitet,
#fyring-soljer og annet brensel,

#kpi%>%
  #pivot_wider(names_from = konsumgruppe )%>%




```
